#!/bin/bash
pyfile=$PYFILE
if [[ -n $pyfile ]]; then
    echo "Compiling $pyfile ..."
    python3 -c "import py_compile; py_compile.compile('$pyfile', '$pyfile' + 'c')"
else
    echo "No Python file specified."
fi
