#!/usr/bin/env python3
import os
import py_compile

pyfile = os.environ.get('PYFILE')
if pyfile:
    pycfile = pyfile + 'c'
    print(f"Compiling {pyfile} ...")
    py_compile.compile(pyfile, pycfile)
